### ISSUE TITLE
You don't have permission to access /PimcoreBulkpump/profile/1

### ISSUE THREAD

**Issue by lrfsh** [YouweGit/PimcoreBulkpump#14]
Hello,

I installed your extension correctly with composer and I get this error when I try to add a profile.

Thank you.

![image](https://cloud.githubusercontent.com/assets/15850553/23309291/c6cc59ce-fab6-11e6-900a-336a340d872d.png)

```
Server threw exception - could not perform action. Please reload the admin interface and try again.

Status: 403 | Forbidden
URL: /PimcoreBulkpump/profile/1?_dc=1487949375268
Params:
Method: DELETE
Message: 


403 Forbidden

Forbidden
You don't have permission to access /PimcoreBulkpump/profile/1
on this server.

```

**Comment by jorisros** [comment]
Hi @laurfx,

I tried to reproduce the bug in a fresh pimcore installation, but adding a new profile works. Can you tell me more about your php version and pimcore version (and buildnumber). So i can reproduce the bug.

Thanks

**Comment by lrfsh** [comment]
Hello,

Here are the system requirements, I am running PHP Version 5.6.14 and Pimcore Version: 4.4.3 (Build: 4044)

![image](https://cloud.githubusercontent.com/assets/15850553/23330501/e0662bca-fb57-11e6-81c8-a9a5fd2266d9.png)

Thank you.

**Comment by jorisros** [comment]
There a new release: 0.4.14 which contain a solution that solve the bug
